### ISSUE TITLE
Add kmcurve functions to main

### ISSUE THREAD

**Issue by clorton** [InstituteforDiseaseModeling/laser#43]
- [x] rename kmcurve (Kaplan-Meier Curve)?
- [x] include tests
- [x] sync with issue #39
- [x] sync with issue #40 
- [ ] sync with issue #41
